"""Shared fixed visual tokens for non-CSS surfaces and parity tests."""

from __future__ import annotations

WHITE = "#FFFFFF"
BLACK = "#000000"
INK = "#262626"
TEXT_MUTED = "#52606D"
TEXT_SUBTLE = "#6B7580"
TEXT_DISABLED = "#A6A6A3"
SURFACE_SUBTLE = "#FBFBFA"
SURFACE_MUTED = "#F5F5F4"
BORDER = "#E5E7EB"
BORDER_STRONG = "#D7D7D4"

SUCCESS = "#28735C"
SUCCESS_SOFT = "#F0F6F4"
DANGER = "#B42318"
DANGER_SOFT = "#FFF6F6"
WARNING = "#9A6700"
WARNING_STRONG = "#8A5200"
WARNING_ACCENT = "#B26A00"
WARNING_FILL = "#F2C037"
WARNING_BORDER = "#D9A91F"
WARNING_SOFT = "#FFF8E8"
INFO = "#2B6F8A"
INFO_SOFT = "#F5FAFC"

ADMIN = "#5B6570"
ADMIN_TINT = "#E8EDF2"
ACADEMIC = "#6B7580"
ACADEMIC_TINT = "#E4E9EE"
VACATION = "#6B7580"
VACATION_TINT = "#EEF2F5"
CONFERENCE = "#4B5967"
CONFERENCE_TINT = "#E0E6EB"
SPECIAL_EVENT = "#607080"
SPECIAL_EVENT_TINT = "#E9EEF2"
CLOSURE_TINT = "#D6D3D1"
PARTIAL_CLOSURE_TINT = "#F1F0EF"

__all__ = [
    "ACADEMIC",
    "ACADEMIC_TINT",
    "ADMIN",
    "ADMIN_TINT",
    "BLACK",
    "BORDER",
    "BORDER_STRONG",
    "CLOSURE_TINT",
    "CONFERENCE",
    "CONFERENCE_TINT",
    "DANGER",
    "DANGER_SOFT",
    "INFO",
    "INFO_SOFT",
    "INK",
    "PARTIAL_CLOSURE_TINT",
    "SPECIAL_EVENT",
    "SPECIAL_EVENT_TINT",
    "SUCCESS",
    "SUCCESS_SOFT",
    "SURFACE_MUTED",
    "SURFACE_SUBTLE",
    "TEXT_DISABLED",
    "TEXT_MUTED",
    "TEXT_SUBTLE",
    "VACATION",
    "VACATION_TINT",
    "WARNING",
    "WARNING_ACCENT",
    "WARNING_BORDER",
    "WARNING_FILL",
    "WARNING_SOFT",
    "WARNING_STRONG",
    "WHITE",
]
